# Generated by Django 5.0.7 on 2024-08-04 01:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('detail', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='images/')),
                ('priority', models.IntegerField(default=0)),
                ('delete_choice', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
