# Generated by Django 5.0.7 on 2024-07-24 11:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='detail',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(),
        ),
    ]
